### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'return_gt_info'

### ISSUE THREAD

**Issue by 94happy** [dvlab-research/UVTR#1]
@yanwei-li @yukang2017 
 First, I appreciate your work very much. But when generating ground-truth dataset, I encountered the following problems: 

> Create GT Database of NuScenesDataset
Traceback (most recent call last):
  File "anaconda3/envs/uvtr_mmdet3d/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'return_gt_info'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "extra_tools/create_data.py", line 85, in <module>
    max_sweeps=args.max_sweeps)
  File "extra_tools/create_data.py", line 43, in nuscenes_data_prep
    f'{out_dir}/{info_prefix}_infos_train.pkl') 
  File "3D_Det/UVTR_mmdetection3d/extra_tools/data_converter/create_unified_gt_database.py", line 70, in create_groundtruth_database
    dataset = build_dataset(dataset_cfg)
  File "3D_Det/UVTR_mmdetection3d/mmdet3d/datasets/builder.py", line 41, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "anaconda3/envs/uvtr_mmdet3d/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: NuScenesDataset: __init__() got an unexpected keyword argument 'return_gt_info'

In addition, in [create_unified_gt_database.py](https://github.com/dvlab-research/UVTR/blob/80a0e85ca4778a997a136b02bc07ab88dd197db3/extra_tools/data_converter/create_unified_gt_database.py#L246), how to obtain the file of nuscenes_img_pro_infos_train.pkl?

**Comment by yanwei-li** [comment]
Sorry for this error. I have fixed the typos in the data sampler. Please try it again.
For data infos, you can use this command in README:
```
python3 extra_tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes_unified
```

**Comment by 94happy** [comment]
@yanwei-li  Thanks for your reply! Now I can run this code smoothly!
