### ISSUE TITLE
Which mmdet3d version should I use?

### ISSUE THREAD

**Issue by foolhard** [dvlab-research/UVTR#23]
Hello, 

Thanks for your great job and sharing the code. 

In Readme, you mentioned we should install mmdet v0.17.3. 
However, in issues #8 , you mentioned mmdet v1.x supported and data converter updated for mmdet v1.x coordination system.

**I am confused which version mmdet3d should be used.** **Could you clarify it?**  

I tried v1.x, but failed to process nuScenes data for UVTR.  And error is:

> _Traceback (most recent call last):
  File "extra_tools/create_data.py", line 5, in <module>
    from data_converter import nuscenes_converter as nuscenes_converter
  File "/dfs/data/open_mmlab/UVTR/mmdetection3d/extra_tools/data_converter/nuscenes_converter.py", line 16, in <module>
    from projects.mmdet3d_plugin.datasets import NuScenesSweepDataset
  File "/dfs/data/open_mmlab/UVTR/mmdetection3d/projects/mmdet3d_plugin/__init__.py", line 9, in <module>
    from .models.detectors import UVTR, UVTRKDCS, UVTRKDL, UVTRKDM
  File "/dfs/data/open_mmlab/UVTR/mmdetection3d/projects/mmdet3d_plugin/models/detectors/__init__.py", line 1, in <module>
    from .uvtr import UVTR
  File "/dfs/data/open_mmlab/UVTR/mmdetection3d/projects/mmdet3d_plugin/models/detectors/uvtr.py", line 13, in <module>
    from projects.mmdet3d_plugin.core.merge_all_augs import merge_all_aug_bboxes_3d
  File "/dfs/data/open_mmlab/UVTR/mmdetection3d/projects/mmdet3d_plugin/core/merge_all_augs.py", line 4, in <module>
    from mmdet3d.ops.iou3d.iou3d_utils import nms_gpu, nms_normal_gpu
ModuleNotFoundError: No module named 'mmdet3d.ops.iou3d'_

**Comment by yanwei-li** [comment]
Hi, it seems mmdet3d replace ```mmdet3d.ops.iou3d``` with ```mmcv.iou3d```. You can directly use the updated one if you use a new version.
