### ISSUE TITLE
'LoadPointsFromFile is not in the pipeline registry'

### ISSUE THREAD

**Issue by qzhang852** [dvlab-research/UVTR#29]
Thank you for your excellent work. When training the multi-modal model, I met an error that
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/workspace/mmdetection3d/projects/mmdet3d_plugin/datasets/pipelines/transform_3d.py", line 608, in __init__
    self.db_sampler = build_from_cfg(db_sampler, OBJECTSAMPLERS)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "UnifiedDataBaseSampler: 'LoadPointsFromFile is not in the pipeline registry'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/workspace/mmdetection3d/projects/mmdet3d_plugin/datasets/nuscenes_dataset.py", line 134, in __init__
    super().__init__(
  File "/workspace/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 99, in __init__
    self.pipeline = Compose(pipeline)
  File "/workspace/mmdetection3d/mmdet3d/datasets/pipelines/compose.py", line 31, in __init__
    transform = build_from_cfg(transform, MMDET_PIPELINES)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: 'UnifiedObjectSample: "UnifiedDataBaseSampler: \'LoadPointsFromFile is not in the pipeline registry\'"'

``` 
I think is is caused by your mmdet3d plugin code, do you have any ideas about that? Thank you in advance.

**Comment by yanwei-li** [comment]
Thanks for your interest. Could you provide the version of mmdet3d used here? Because different mmdet3d versions seem to have different methods to load this function. This works well for me when using mmdet3d<=v1.0.0.

**Comment by qzhang852** [comment]
Hi, I used the 1.0.0rc5 of mmdet3d. I found that I used the wrong ```train.py```  script, and it's solved.
